# Generated by Django 2.1.2 on 2018-12-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sel', '0004_auto_20181210_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField(max_length=40)),
                ('logo', models.FileField(blank=True, null=True, upload_to=' Profile_image')),
            ],
        ),
        migrations.AddField(
            model_name='get',
            name='Ch',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='get',
            name='K',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='get',
            name='M',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='get',
            name='Pot',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='get',
            name='Sh',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='get',
            name='T',
            field=models.IntegerField(default=1),
        ),
    ]
