# Generated by Django 2.1.2 on 2018-12-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sel', '0005_auto_20181210_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='get',
            name='Ch',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='get',
            name='K',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='get',
            name='M',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='get',
            name='Pot',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='get',
            name='Sh',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='get',
            name='T',
            field=models.BooleanField(),
        ),
    ]
